// pluto_lua.h — embedded pluto.lua (clean-room subset), auto-generated.
// pluto.persist / pluto.unpersist: save-data serializer subset.
#pragma once

static const char PLUTO_LUA_SRC[] =
"-- pluto.lua — clean-room subset of the pluto serializer API.\n"
"--\n"
"-- Behavior contract (from the official pluto doc bundled with the engine and\n"
"-- the adv framework usage `pluto.persist({}, obj)` / `pluto.unpersist({}, str)`):\n"
"--   pluto.persist(perm, value) -> string   serialized form of value\n"
"--   pluto.unpersist(perm, str) -> value    reconstructed value\n"
"-- Supported value types: nil, boolean, number, string, and tables\n"
"-- (nested, shared references and cycles preserved). Any other type\n"
"-- (functions, userdata, threads) serializes as nil.\n"
"-- The wire format is Lua source evaluated by loadstring; saves are only\n"
"-- ever read back by this same implementation, so the encoding is free.\n"
"\n"
"pluto = {}   -- global: registered by the engine at Lua init\n"
"\n"
"local function is_identifier_name(n)\n"
"  return type(n) == \"string\" and n:match(\"^t%d+$\") ~= nil\n"
"end\n"
"\n"
"function pluto.persist(perm, value)\n"
"  local ids = {}      -- object -> variable name\n"
"  local seq = 0\n"
"\n"
"  -- pass 1: assign a variable name to every reachable table\n"
"  local function assign(v)\n"
"    if type(v) ~= \"table\" or ids[v] then return end\n"
"    seq = seq + 1\n"
"    ids[v] = \"t\" .. seq\n"
"    for k, vv in pairs(v) do\n"
"      assign(k)\n"
"      assign(vv)\n"
"    end\n"
"  end\n"
"  assign(value)\n"
"  if type(value) ~= \"table\" then\n"
"    seq = seq + 1\n"
"    ids[value] = \"t\" .. seq -- non-table roots still get a slot; harmless\n"
"  end\n"
"\n"
"  local stmts = {}\n"
"  local emitted = {}\n"
"\n"
"  local function emit(v)\n"
"    local t = type(v)\n"
"    if t == \"nil\" then return \"nil\"\n"
"    elseif t == \"boolean\" then return v and \"true\" or \"false\"\n"
"    elseif t == \"number\" then return string.format(\"%.17g\", v)\n"
"    elseif t == \"string\" then return string.format(\"%q\", v)\n"
"    elseif t == \"table\" then\n"
"      local id = ids[v]\n"
"      if emitted[id] then return id end\n"
"      emitted[id] = true\n"
"      stmts[#stmts + 1] = id .. \" = {}\"\n"
"      for k, vv in pairs(v) do\n"
"        -- evaluate children FIRST: emit() appends their definition lines.\n"
"        -- Appending the parent assignment with a precomputed #stmts index\n"
"        -- would overwrite the just-appended child definition (the bug that\n"
"        -- dropped empty nested tables such as conf.keys from saves).\n"
"        local ek = emit(k)\n"
"        local ev = emit(vv)\n"
"        stmts[#stmts + 1] = id .. \"[\" .. ek .. \"] = \" .. ev\n"
"      end\n"
"      return id\n"
"    end\n"
"    return \"nil\"\n"
"  end\n"
"\n"
"  local root = emit(value)\n"
"  return table.concat(stmts, \"\\n\") .. \"\\nreturn \" .. root\n"
"end\n"
"\n"
"function pluto.unpersist(perm, str)\n"
"  if type(str) ~= \"string\" or str == \"\" then return nil end\n"
"  local chunk, err = loadstring(str)\n"
"  if not chunk then return nil, err end\n"
"  return chunk()\n"
"end\n"
"\n"
"return pluto\n"
"\n"
;